import { Question } from '../types';

export const QUESTIONS_DATA: Question[] = [
  {
    id: 1,
    prompt: "Do you think I'm a good best friend? 🥺",
    yesText: "YES! Of course ✨",
    yesReaction: "Obviously ❤️",
    yesEmoji: "🥰",
    noText: "Hmm... 🤨",
    noReaction: "Error 404: Disagreeing not allowed!",
    noEmoji: "🤨",
    badge: "Question 1 / 9",
  },
  {
    id: 2,
    prompt: "Would you take me out for dinner? 🍕",
    yesText: "YES, dinner on me! 🍕",
    yesReaction: "Let's gooo 🍕",
    yesEmoji: "🥳",
    noText: "Excuse me?! 😭",
    noReaction: "My stomach is offended!",
    noEmoji: "🍕",
    badge: "Question 2 / 9",
  },
  {
    id: 3,
    prompt: "Would you share your fries with me? 🍟",
    yesText: "Always share fries 🍟",
    yesReaction: "You're officially amazing ❤️",
    yesEmoji: "🍟",
    noText: "Okay... I'll remember this 😭",
    noReaction: "Fry tax will still be collected!",
    noEmoji: "🥺",
    badge: "Question 3 / 9",
  },
  {
    id: 4,
    prompt: "Would you survive a whole day with me without getting annoyed? 😂",
    yesText: "Easy, 100% yes 😂",
    yesReaction: "Respect 🫡",
    yesEmoji: "🤝",
    noText: "I knew it 💀",
    noReaction: "Hey! I'm delightful company!",
    noEmoji: "💀",
    badge: "Question 4 / 9",
  },
  {
    id: 5,
    prompt: "If I said 'let's go on an adventure', would you come? 🚗✨",
    yesText: "Pack the snacks, YES! 🚗",
    yesReaction: "That's my bestie ❤️",
    yesEmoji: "🌟",
    noText: "Traitor 😭",
    noReaction: "I'm coming to drag you along anyway!",
    noEmoji: "🚗",
    badge: "Question 5 / 9",
  },
  {
    id: 6,
    prompt: "Would you let me choose the movie? 🎬",
    yesText: "YES (I trust your taste) 🍿",
    yesReaction: "You have questionable trust, but okay 😂",
    yesEmoji: "🍿",
    noText: "Wow. Betrayal. 😭",
    noReaction: "My cinema picks are masterpieces!",
    noEmoji: "🎬",
    badge: "Question 6 / 9",
  },
  {
    id: 7,
    prompt: "Would you buy me ice cream? 🍦",
    yesText: "Double scoop for you! 🍦",
    yesReaction: "Correct answer 😌🍦",
    yesEmoji: "🍨",
    noText: "Unacceptable behavior 😭",
    noReaction: "No ice cream?! The sadness...",
    noEmoji: "🍦",
    badge: "Question 7 / 9",
  },
  {
    id: 8,
    prompt: "Would you still be my best friend if I annoyed you for 24 hours straight? 😂",
    yesText: "YES, unfortunately ❤️",
    yesReaction: "You are officially stuck with me ❤️",
    yesEmoji: "🫂",
    noText: "Too late. You're already stuck with me 😌",
    noReaction: "Contract signed, non-refundable!",
    noEmoji: "😈",
    badge: "Question 8 / 9",
  },
  {
    id: 9,
    prompt: "Okay... one serious question.",
    delayPrompt: "Am I your favorite idiot? 🥹",
    yesText: "YES, absolute favorite! 💖",
    yesReaction: "I KNEW IT ❤️😂",
    yesEmoji: "👑",
    noText: "That answer has been rejected by the system 🤖",
    noReaction: "System error: Answer not mathematically possible 🚫",
    noEmoji: "🤖",
    badge: "Question 9 / 9 (FINAL)",
  },
];

export const FUNNY_NO_MESSAGES = [
  "NO 🙄",
  "Nice try 😂",
  "Too slow 😭",
  "Why are you like this? 💀",
  "JUST SAY YES 😭❤️",
  "Nope 😂",
  "Catch me!",
  "Almost!",
  "Not today 😌",
  "You missed!",
  "Why are you chasing me? 💀",
  "I'm shy 👉👈",
  "Absolutely not 😂",
  "Okay you REALLY want to say no huh 😭",
  "Try the big shiny YES button! 👉",
  "Error: NO.exe has stopped working 🤖",
];

export const BESTIE_STATUS_MESSAGES = [
  { text: "Bestie.exe is running smoothly... 🚀", icon: "✨" },
  { text: "Calculating friendship level... 100% ❤️", icon: "📊" },
  { text: "System detected: Certified Bestie 👑", icon: "💖" },
  { text: "Friendship level: Maximum capacity 💫", icon: "🌸" },
  { text: "Scanning cuteness... 100% Verified ✨", icon: "🎀" },
  { text: "Snack sharing protocol: ENABLED 🍟", icon: "🍟" },
  { text: "Vibe check: Immaculate Bestie Energy 💅", icon: "🌈" },
  { text: "Warning: Bestie vibes overload detected 💖", icon: "⚠️" },
];
